<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\backend\Archive.Backend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>ad40ebd3-1660-4b27-9ad5-779c1f069714</UserSecretsId>
  </PropertyGroup>

</Project>
